CREATE TABLE `Player` (
	`PlayerID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Name`	TEXT NOT NULL,
	`CountryCode`	TEXT NOT NULL,
	`Gender`	TEXT NOT NULL,
	`DateofBirth`	TEXT NOT NULL
);
CREATE TABLE `Country` (
	`CountryCode`	TEXT NOT NULL,
	`CountryName`	TEXT NOT NULL,
	`PlayerIDofCaptain`	INTEGER,
	FOREIGN KEY(`PlayerIDofCaptain`) REFERENCES `Player`(`PlayerID`),
	PRIMARY KEY(`CountryCode`)
);
CREATE TABLE `Game` (
	`GameID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`PlayerID`	INTEGER NOT NULL UNIQUE,
	`DatePlayed`	TEXT NOT NULL,
	`StartTime`	TEXT NOT NULL,
	`Score`	INTEGER NOT NULL,
	FOREIGN KEY(`PlayerID`) REFERENCES `Player`(`PlayerID`)
);