CREATE TABLE `Country` (
	`CountryCode`	TEXT NOT NULL,
	`CountryName`	TEXT NOT NULL,
	`CaptainID`	INTEGER ,
	PRIMARY KEY(`CountryCode`)
);

CREATE TABLE `Game` (
	`GameID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`PlayerID`	INTEGER NOT NULL,
	`DatePlayed`	TEXT NOT NULL,
	`StartTime`	TEXT NOT NULL,
	`Score`	INTEGER NOT NULL
);

CREATE TABLE `Player` (
	`PlayerID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Name`	TEXT NOT NULL,
	`CountryCode`	TEXT NOT NULL,
	`Gender`	INTEGER NOT NULL,
	`DateOfBirth`	INTEGER NOT NULL,
	FOREIGN KEY(`CountryCode`) REFERENCES `Country`(`CountryCode`)
);