CREATE TABLE `Country` (
	`CountryCode`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`CountryName`	TEXT NOT NULL,
	`CaptainID`	INTEGER,
	FOREIGN KEY(`CaptainID`) REFERENCES `Player`(`PlayerID`)
);
CREATE TABLE `Game` (
	`GameID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`PlayerID`	INTEGER NOT NULL,
	`DatePlayed`	TEXT NOT NULL,
	`StartTime`	TEXT NOT NULL,
	`Score`	INTEGER NOT NULL,
	FOREIGN KEY(`PlayerID`) REFERENCES `Player`(`PlayerID`)
);
CREATE TABLE `Player` (
	`PlayerID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`	TEXT NOT NULL,
	`CountryCode`	INTEGER NOT NULL,
	`GENDER`	TEXT NOT NULL,
	`DoB`	TEXT NOT NULL,
	FOREIGN KEY(`CountryCode`) REFERENCES `Country`(`CountryCode`)
);