queue1 = Queue()
queue1.display()

queue1.enqueue('Juice')
queue1.enqueue('Milk')
queue1.enqueue('Chips')
queue1.enqueue('Eggs')
queue1.enqueue('Bread')
queue1.enqueue('Cereal')
queue1.enqueue('Pizza')
queue1.enqueue('Water')
queue1.enqueue('Fruits')
queue1.enqueue('Yoghurt')

queue1.display()